### PR TITLE
Vault path templating

### PR DESCRIPTION
**Pull request by Tolyar**
# Pull Request Template

## Description

Allow to set vault paths inside charts instead of using autogenerated one. Now it is possible to use not only deliminators and vaultpath as path generator but --vaulttemplate pattern for path setting. By default  vaut template is VAULT:

How it works.

key1: VAULT:helm1/test/key1
key2: VAULT:/helm2/test/key2

key1 - will be storing in base_path/helm1/test/key1 (by default secrets/helm1/key1)
key2 - will be storing in /helm2/test/key2 . Where is helm2 - secrets base added like this: **vault secrets enable  -path=helm2 kv-v2**

This feature does not brake deliminators support but only allow new way for key path definition.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [+ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:
v3.2.4

* Python Version:
3.7.3

* Vault Version:
1.4.2

## Checklist:

- [ +] My code follows the style guidelines of this project
- [ +] I have performed a self-review of my own code
- [ +] I have commented my code, particularly in hard-to-understand areas
- [ +] I have made corresponding changes to the documentation
- [ +] My changes generate no new warnings
- [ +] I have added tests that prove my fix is effective or that my feature works
- [ +] New and existing unit tests pass locally with my changes
- [ +] Any dependent changes have been merged and published in downstream modules

## Mentions:

@Just-Insane

### CODE REVIEW

**Comment by Just-Insane** [comment]
LGTM!

**Comment by Just-Insane** [comment]
There appears to be issues with the tests in this PR.

~Please see https://gitlab.com/just.insane/helm-vault/-/jobs/701208682 for details.~
**Note:** The previous GitLab project had to be deleted and re-created to get PR CI working.

**Comment by Just-Insane** [comment]
@Tolyar Sorry about that, I'm not sure why the automated tests didn't run on this PR. Can you resubmit with the test fixes?

**Comment by Tolyar** [comment]
This happened because route secrets is not available in yours vault server.  This can be added via `vault secrets enable  -path=secrets kv-v2`.
Looks like the best way is change user: VAULT:/secrets/testdata/user to user: VAULT:/secret/testdata/user . I believe that /secret/ presents on your server, because secret_mount is "secret/helm” by default. It’s possible to check via `vault secrets list`. Should I recreate PR?

**Comment by Just-Insane** [comment]
Ah yes, that would make sense. The default K/V mount point is `secret/`, as mentioned here: https://www.vaultproject.io/docs/secrets/kv/kv-v2

The automated test environment is just running a dev-mode server so it creates a K/V v2 mount at `secret/` automatically, which is what I have been using for tests.

Please recreate the PR. Sorry again for not catching that before merging.

**Pull request merged**
